#!/bin/bash

if [ -f /var/www/package.json ]; then
    if [ ! "$(ls -A /var/www/node_modules)" ]; then
        yarn install
    else
        echo "Modules exists... skipping install"
    fi
else
    echo "No package.json file found in /var/www"
    exit 1;
fi